export const ADMIN_ROUTES = {
  root: "/admin",
  login: "/admin/login",
  forgotPassword: "/admin/forgot-password",
  resetPassword: "/admin/reset-password",
  unauthorized: "/admin/unauthorized",
  dashboard: "/admin/dashboard",
  hero: "/admin/hero",
  expertiseCarousel: "/admin/expertise-carousel",
  footer: "/admin/footer",
  about: "/admin/about",
  aboutHome: "/admin/about-home",
  projects: "/admin/projects",
  experience: "/admin/experience",
  skills: "/admin/skills",
  resume: "/admin/resume",
  blog: "/admin/blog",
  contact: "/admin/contact",
  media: "/admin/media",
  seo: "/admin/seo",
  settings: "/admin/settings",
  users: "/admin/users",
} as const;

export type AdminRouteKey = keyof typeof ADMIN_ROUTES;
